# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 450)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header = QtWidgets.QLabel(parent=self.centralwidget)
        self.header.setGeometry(QtCore.QRect(10, 9, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.header.setObjectName("header")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_label.setFont(font)
        self.id_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                   QtCore.Qt.AlignmentFlag.AlignTrailing|
                                   QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.id_label.setObjectName("id_label")
        self.sort_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.sort_label.setGeometry(QtCore.QRect(10, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sort_label.setFont(font)
        self.sort_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                     QtCore.Qt.AlignmentFlag.AlignTrailing|
                                     QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sort_label.setObjectName("sort_label")
        self.roasting_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.roasting_label.setGeometry(QtCore.QRect(10, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roasting_label.setFont(font)
        self.roasting_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                         QtCore.Qt.AlignmentFlag.AlignTrailing|
                                         QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.roasting_label.setObjectName("roasting_label")
        self.hammering_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.hammering_label.setGeometry(QtCore.QRect(10, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hammering_label.setFont(font)
        self.hammering_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                          QtCore.Qt.AlignmentFlag.AlignTrailing|
                                          QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.hammering_label.setObjectName("hammering_label")
        self.description_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.description_label.setGeometry(QtCore.QRect(10, 210, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.description_label.setFont(font)
        self.description_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                            QtCore.Qt.AlignmentFlag.AlignTrailing|
                                            QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.description_label.setObjectName("description_label")
        self.roast = QtWidgets.QComboBox(parent=self.centralwidget)
        self.roast.setGeometry(QtCore.QRect(110, 130, 221, 31))
        self.roast.setObjectName("roast")
        self.roast.addItem("")
        self.roast.addItem("")
        self.roast.addItem("")
        self.form = QtWidgets.QComboBox(parent=self.centralwidget)
        self.form.setGeometry(QtCore.QRect(110, 170, 221, 31))
        self.form.setObjectName("form")
        self.form.addItem("")
        self.form.addItem("")
        self.sort = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sort.setGeometry(QtCore.QRect(110, 90, 221, 31))
        self.sort.setObjectName("sort")
        self.id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id.setGeometry(QtCore.QRect(110, 50, 221, 31))
        self.id.setObjectName("id")
        self.description = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.description.setGeometry(QtCore.QRect(110, 210, 221, 91))
        self.description.setObjectName("description")
        self.price_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.price_label.setGeometry(QtCore.QRect(10, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price_label.setFont(font)
        self.price_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                      QtCore.Qt.AlignmentFlag.AlignTrailing|
                                      QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.price_label.setObjectName("price_label")
        self.packing_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.packing_label.setGeometry(QtCore.QRect(10, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.packing_label.setFont(font)
        self.packing_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|
                                        QtCore.Qt.AlignmentFlag.AlignTrailing|
                                        QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.packing_label.setObjectName("packing_label")
        self.price = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.price.setGeometry(QtCore.QRect(110, 310, 221, 31))
        self.price.setObjectName("price")
        self.packing = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.packing.setGeometry(QtCore.QRect(110, 350, 221, 31))
        self.packing.setObjectName("packing")
        self.confirm_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirm_btn.setGeometry(QtCore.QRect(10, 390, 321, 41))
        self.confirm_btn.setObjectName("confirm_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.status = QtWidgets.QStatusBar(parent=MainWindow)
        self.status.setObjectName("status")
        MainWindow.setStatusBar(self.status)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Редактор"))
        self.header.setText(_translate("MainWindow", "Редактор"))
        self.id_label.setText(_translate("MainWindow", "ID: "))
        self.sort_label.setText(_translate("MainWindow", "Сорт:"))
        self.roasting_label.setText(_translate("MainWindow", "Обжарка:"))
        self.hammering_label.setText(_translate("MainWindow", "Форма:"))
        self.description_label.setText(_translate("MainWindow", "Описание:"))
        self.roast.setItemText(0, _translate("MainWindow", "Светлая"))
        self.roast.setItemText(1, _translate("MainWindow", "Средняя"))
        self.roast.setItemText(2, _translate("MainWindow", "Тёмная"))
        self.form.setItemText(0, _translate("MainWindow", "В зёрнах"))
        self.form.setItemText(1, _translate("MainWindow", "Молотый"))
        self.price_label.setText(_translate("MainWindow", "Цена (₽):"))
        self.packing_label.setText(_translate("MainWindow", "Объём (г):"))
        self.confirm_btn.setText(_translate("MainWindow", "Готово"))
