# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 981, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 50, 980, 410))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.new_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.new_btn.setGeometry(QtCore.QRect(730, 470, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_btn.setFont(font)
        self.new_btn.setObjectName("new_btn")
        self.edit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit_btn.setGeometry(QtCore.QRect(10, 470, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_btn.setFont(font)
        self.edit_btn.setObjectName("edit_btn")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(280, 470, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.id_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.id_box.setGeometry(QtCore.QRect(310, 480, 61, 22))
        self.id_box.setObjectName("id_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.status = QtWidgets.QStatusBar(parent=MainWindow)
        self.status.setObjectName("status")
        MainWindow.setStatusBar(self.status)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кофейня"))
        self.label.setText(_translate("MainWindow", "Кофейня"))
        self.new_btn.setText(_translate("MainWindow", "Создать новую запись"))
        self.edit_btn.setText(_translate("MainWindow", "Редактировать запись по ID"))
        self.id_label.setText(_translate("MainWindow", " ID:"))
